import re
import secrets

ADJECTIVES = (
    "amber",
    "arctic",
    "azure",
    "bold",
    "brave",
    "brisk",
    "calm",
    "cosy",
    "crimson",
    "crisp",
    "dapper",
    "dusky",
    "eager",
    "fierce",
    "frosty",
    "gentle",
    "golden",
    "happy",
    "hazy",
    "icy",
    "jaunty",
    "jolly",
    "keen",
    "lively",
    "lucky",
    "merry",
    "misty",
    "noble",
    "plucky",
    "quiet",
    "rapid",
    "rosy",
    "rustic",
    "sage",
    "scarlet",
    "silent",
    "silver",
    "sleek",
    "snappy",
    "stout",
    "sunny",
    "swift",
    "teal",
    "tidy",
    "vivid",
    "warm",
    "zesty",
)
NOUNS = (
    "acorn",
    "anchor",
    "badger",
    "beacon",
    "blossom",
    "boulder",
    "brook",
    "canyon",
    "cedar",
    "cinder",
    "cipher",
    "comet",
    "cove",
    "crane",
    "delta",
    "ember",
    "falcon",
    "fawn",
    "fern",
    "fjord",
    "forge",
    "glade",
    "harbour",
    "heron",
    "hollow",
    "ibis",
    "kestrel",
    "lantern",
    "ledger",
    "linnet",
    "loft",
    "marsh",
    "meadow",
    "mosaic",
    "nimbus",
    "orchard",
    "otter",
    "owl",
    "pine",
    "puffin",
    "quartz",
    "quill",
    "raven",
    "ridge",
    "river",
    "shore",
    "sparrow",
    "spruce",
    "thorn",
    "valley",
    "willow",
    "wren",
)


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-") or "feed"


def generate(seed_text: str | None = None) -> str:
    base = slugify(seed_text) if seed_text else f"{secrets.choice(ADJECTIVES)}-{secrets.choice(NOUNS)}"
    return f"{base}-{secrets.token_hex(4)}"
